name: Build & Upload VRChat World

on:
  push:
    branches:
      - main
  release:
    types: [published]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build-and-upload-nightly-world:
    runs-on: ubuntu-latest

    env:
      unity-docker-image: unityci/editor:ubuntu-2022.3.22f1-windows-mono-3.1.0
      workspace-path: "${{ github.workspace }}/workspace"
      source-path: "${{ github.workspace }}/source"
      add-packages-script-path: "${{ github.workspace }}/source/.github/workflow-scripts/add-user-package-to-vrc-get.js"
      get-serial-script-path: "${{ github.workspace }}/source/.github/workflow-scripts/get-serial-from-license-file.js"
      UNITY_SERIAL: XXXXX-XXXXX-XXXXX-XXXXX-XXXXX

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        if: github.event_name != 'release'
        with:
          path: ${{ env.source-path }}

      - name: Download Release Package
        uses: robinraju/release-downloader@a96f54c1b5f5e09e47d9504526e96febd949d4c2
        if: github.event_name == 'release'
        with:
          latest: true
          preRelease: false
          out-file-path: ${{ env.source-path }}
          fileName: "*.zip"
          extract: true

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.UNITYCI_TEST_DEPLOY_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Clone external repo
        run: |
          git clone git@github.com:benjithatfoxguy/VRC-GH-Actions-World-Test.git ${{env.workspace-path}}

      - name: Setup vrc-get
        uses: anatawa12/sh-actions/setup-vrc-get@master

      - name: Add VPM Repositories
        run: |
          vrc-get repo add https://adjerry91.github.io/VRCFaceTracking-Templates/index.json
          vrc-get repo add https://api.vrlabs.dev/listings/category/Components
          vrc-get repo add https://api.vrlabs.dev/listings/category/Dependencies
          vrc-get repo add https://api.vrlabs.dev/listings/category/Essentials
          vrc-get repo add https://api.vrlabs.dev/listings/category/Systems
          vrc-get repo add https://codec-xyz.github.io/photo_frame_manager/index.json
          vrc-get repo add https://drblackrat.github.io/vpm-listing/index.json
          vrc-get repo add https://enitimeago.github.io/vpm-repos/index.json
          vrc-get repo add https://esperecyan.github.io/VRMConverterForVRChat/registry.json
          vrc-get repo add https://furality.github.io/vcc-packages/index.json
          vrc-get repo add https://github.com/Krysiek/CuteDancer/raw/vpm/CuteDancer.json
          vrc-get repo add https://hai-vr.github.io/vpm-listing/index.json
          vrc-get repo add https://kemocade.github.io/Kemocade.Vrc.Data.Extensions/index.json
          vrc-get repo add https://krysiek.github.io/CuteDancer/index.json
          vrc-get repo add https://kurone-kito.github.io/vpm/index.json
          vrc-get repo add https://kurotu.github.io/vpm-repos/vpm.json
          vrc-get repo add https://labthe3rd.github.io/PZCameraSystem/index.json
          vrc-get repo add https://lilxyzw.github.io/vpm-repos/vpm.json
          vrc-get repo add https://magmamcnet.github.io/VPM/index.json
          vrc-get repo add https://mmmaellon.github.io/MMMaellonVCCListing/index.json
          vrc-get repo add https://orels1.github.io/orels-Unity-Shaders/index.json
          vrc-get repo add https://poiyomi.github.io/vpm/index.json
          vrc-get repo add https://pokeyi.dev/vpm-packages/index.json
          vrc-get repo add https://repo.buddyworks.wtf/index.json
          vrc-get repo add https://spokeek.github.io/vpm-repository/index.json
          vrc-get repo add https://suzuryg.github.io/vpm-repos/vpm.json
          vrc-get repo add https://vcc.pawlygon.net/index.json
          vrc-get repo add https://vcc.vrcfury.com/
          vrc-get repo add https://vpm.anatawa12.com/vpm.json
          vrc-get repo add https://vpm.benjifox.gay/index.json
          vrc-get repo add https://vpm.dreadscripts.com/listings/main.json
          vrc-get repo add https://vpm.nadena.dev/vpm.json
          vrc-get repo add https://vpm.pimaker.at/index.json
          vrc-get repo add https://vpm.techanon.dev/index.json
          vrc-get repo add https://vpm.thry.dev/index.json
          vrc-get repo add https://wholesomevr.github.io/SPS-Configurator/index.json
          vrc-get repo add https://i5ucc.github.io/vpm/main.json
          vrc-get repo add https://pandrabox.github.io/vpm/index.json
          vrc-get repo add https://kb10uy.github.io/vrc-repository/index.json
          vrc-get repo add https://tr1turbo.github.io/BlendShare/index.json
          vrc-get repo add https://waya0125.com/vpm
          vrc-get repo add https://foxscore.dev/vpm/index.json
          vrc-get repo add https://tliks.github.io/vpm-repos/index.json
          vrc-get repo add https://www.matthewherber.com/Happys-VRC-tools/index.json
          vrc-get repo add https://d4rkc0d3r.github.io/vpm-repos/main.json
          vrc-get repo add https://vpm.narazaka.net/index.json
          vrc-get repo add https://xtlcdn.github.io/vpm/index.json
          vrc-get repo add https://vpm.bluwizard.net/index.json
          vrc-get repo add https://aurycat.github.io/vpm/index.json
          vrc-get repo add https://lastationvrchat.github.io/Lastation-Package-Listing/index.json
          vrc-get repo add https://vpm.ureishi.net/repos.json
          vrc-get repo add https://vpm.vrsl.dev/index.json
          vrc-get repo add https://nidonocu.github.io/virtual-gryphon-packages/index.json
          vrc-get repo add https://z3y.github.io/vpm-package-listing/index.json
          vrc-get repo add https://page.853lab.com/vpm-repos/vpm.json
          vrc-get repo add https://hoyotoon.github.io/vpm/index.json
          vrc-get repo add https://tmyt.github.io/vpm/index.json
          vrc-get repo add https://rerigferl.github.io/vpm/vpm.json
          vrc-get repo add https://vrctxl.github.io/VPM/index.json
          vrc-get repo add https://guribo.github.io/TLP/index.json
          vrc-get repo add https://cyanlaser.github.io/CyanPlayerObjectPool/index.json
          vrc-get repo add https://reava.github.io/VPM-Listings/index.json
          vrc-get repo add https://vavassor.github.io/OrchidSealVPM/index.json
          vrc-get repo add https://virtualvisions.github.io/VPM-Packages/index.json
          vrc-get repo add https://vpm.gyoku.tech/vpm.json
          vrc-get repo add https://pkg-index.yuxiaviation.com/
          vrc-get repo add https://orels1.github.io/UdonToolkit/index.json
          vrc-get repo add https://vrcd-community.github.io/vpm-packages/index.json
          vrc-get repo list

      - name: Resolve VPM Dependencies
        working-directory: ${{ env.workspace-path }}
        run: "vrc-get resolve"

      - name: Remove Unsupported Packages
        working-directory: ${{ env.workspace-path }}
        run: |
          vrc-get remove dev.foxscore.easy-login -y
          vrc-get remove au.benjithatfoxguy.templates.world.2022.3.22f1.updater -y
          vrc-get remove com.nidonocu.vrcunitytoolbar -y
          vrc-get remove au.benjithatfoxguy.batchimportunitypackage -y
          vrc-get remove au.benjithatfoxguy.restartunity -y
          vrc-get remove dev.hai-vr.resilience.let-me-see -y
          vrc-get remove dev.hai-vr.resilience.toolkit -y
          vrc-get remove unity-editor-dark-mode -y
          rm -rf Assets/Editor
          rm -rf Assets/Editor.meta
          rm -rf Assets/UERP
          rm -rf Assets/UERP.meta
        
      - name: Downgrade VRCSDK to 3.7.1
        working-directory: ${{ env.workspace-path }}
        run: |
          vrc-get remove com.vrchat.worlds -y
          vrc-get remove com.vrchat.base -y
          vrc-get install com.vrchat.worlds 3.7.1 -y
          vrc-get install com.vrchat.base 3.7.1 -y

      - name: Add Source Package to vrc-get
        if: github.event_name == 'release'
        run: "node ${{ env.add-packages-script-path }} ${{ env.source-path }}/src/Packages/com.yuxiaviation.v320neo.fdmi"

      - name: Add Release Pacakge to vrc-get
        if: github.event_name == 'release'
        run: "node ${{ env.add-packages-script-path }} ${{ env.source-path }}"

      - name: Add Source Pacakge to Workspace
        if: github.event_name == 'release'
        working-directory: ${{ env.workspace-path }}
        run: "vrc-get install com.yuxiaviation.v320neo.fdmi -y"

      - name: Add AutoBuild Packages to Workspace
        working-directory: ${{ env.workspace-path }}
        run: vrc-get install com.yuxiaviation.vrchat.autobuild.world -y

      - name: Add Patcher Package to fix SDK Build on Linux
        working-directory: ${{ env.workspace-path }}
        run: vrc-get install cn.org.vrcd.vpm.vrchat-sdk-patcher.worlds -y

      - name: Cache Library
        uses: actions/cache@v4
        with:
          path: ${{ env.workspace-path }}/Library
          key: Library-Build-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-Build-

      - name: Get Unity Serial
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        run: |
          UNITY_SERIAL="$(echo $UNITY_LICENSE | node ${{ env.get-serial-script-path }})"
          echo "::add-mask::$UNITY_SERIAL"
          echo "UNITY_SERIAL=$UNITY_SERIAL" >> $GITHUB_ENV

      - name: Build & Upload VRChat World
        run: |
          docker run \
            -v ${{ env.workspace-path }}:/project \
            -v ${{ github.workspace }}/tmp:/tmp/DefaultCompany/ \
            -e VRC_AUTO_BUILD_USERNAME=$VRC_AUTO_BUILD_USERNAME \
            -e VRC_AUTO_BUILD_PASSWORD=$VRC_AUTO_BUILD_PASSWORD \
            -e VRC_AUTO_BUILD_TOTP_KEY=$VRC_AUTO_BUILD_TOTP_KEY \
            -e VRC_AUTO_BUILD_SCENE_PATH=$VRC_AUTO_BUILD_SCENE_PATH \
            -e VRC_AUTO_BUILD_CONTENT_ID=$VRC_AUTO_BUILD_CONTENT_ID \
            ${{ env.unity-docker-image }} \
            unity-editor -projectPath /project \
            -username ${{ secrets.UNITY_EMAIL }} -password ${{ secrets.UNITY_PASSWORD }} -serial ${{ env.UNITY_SERIAL }} \
            -batchmode -logFile - \
            -buildTarget Win64 \
            -executeMethod VRChatAerospaceUniversity.VRChatAutoBuild.Worlds.AutoBuildVRChatWorld.BuildWorld
        env:
          VRC_AUTO_BUILD_CONTENT_ID: ${{ secrets.NIGHTLY_WORLD_CONTENT_ID }}
          VRC_AUTO_BUILD_SCENE_PATH: ${{ secrets.WORKSPACE_SCENE_PATH }}
          VRC_AUTO_BUILD_USERNAME: ${{ secrets.VRCHAT_USERNAME }}
          VRC_AUTO_BUILD_PASSWORD: ${{ secrets.VRCHAT_PASSWORD }}
          VRC_AUTO_BUILD_TOTP_KEY: ${{ secrets.VRCHAT_TOTP_KEY }}